### ISSUE TITLE
build issues..

### ISSUE THREAD

**Issue by walshe** [GaloyMoney/galoy#241] opened 2021-06-16 10:44 UTC
so yarn add-charts has run successfully and everything is green in my minikube dashboard,  but yarn run build is still giving me problems:

add charts: (all good)
````
Emmett@MDs-MacBook-Pro galoy % yarn add-charts
yarn run v1.22.10
$ export LOCAL=true && source ./exportLocal.sh && ./initLocalTest.sh
..
..
NAME: galoy
LAST DEPLOYED: Wed Jun 16 11:18:35 2021
NAMESPACE: default
STATUS: deployed
REVISION: 2
waiting for -n=default -l app.kubernetes.io/instance=galoy
pod/galoy-admin-panel-7c777c9d99-g2q72 condition met
pod/galoy-lnpage-dcc859664-gzc4s condition met
pod/galoy-lnpay-7c5578cf49-d6jrw condition met
pod/galoy-mongodb-0 condition met
pod/galoy-price-76d7d8cbb5-bsfh6 condition met
pod/galoy-redis-node-0 condition met
✨  Done in 506.76s.
````

Yarn build issues:

````
Emmett@MDs-MacBook-Pro galoy % yarn --version
1.22.10
Emmett@MDs-MacBook-Pro galoy % node --version
v14.0.0
Emmett@MDs-MacBook-Pro galoy % yarn install
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.68s.
Emmett@MDs-MacBook-Pro galoy % yarn run build
yarn run v1.22.10
$ tsc -p tsconfig-build.json && cp -R src/protos lib && cp src/schema.graphql lib
src/AdminOps.ts:11:26 - error TS2339: Property 'findByUsername' does not exist on type 'Model<any, any, any>'.

11     return !!(await User.findByUsername({ username }))
                            ~~~~~~~~~~~~~~

src/AdminOps.ts:27:29 - error TS2339: Property 'findByUsername' does not exist on type 'Model<any, any, any>'.

27     const user = await User.findByUsername({ username });
                               ~~~~~~~~~~~~~~

src/entrypoint/dailyBalanceNotification.ts:18:28 - error TS2339: Property 'getActiveUsers' does not exist on type 'Model<any, any, any>'.

18   const users = await User.getActiveUsers({})
                              ~~~~~~~~~~~~~~

src/entrypoint/graphql.ts:165:39 - error TS2339: Property 'getUser' does not exist on type 'Model<any, any, any>'.

165       const { _id: uid } = await User.getUser({ username, phone })
````

**Comment by nicolasburtey** [comment] 2021-06-19 09:28
@walshe a PR that has improved a lot of the types has just been merged. can you check if you still have the same issue with the master branch?

**Comment by walshe** [comment] 2021-06-21 13:39
thanks @nicolasburtey , the build part now works but looks like some of my pods are gone awry now or something as it seems to be hanging.. what is the easiest way to destroy everything and start again?

````
Emmett@MDs-MacBook-Pro galoy % yarn add-charts
yarn run v1.22.10
$ export LOCAL=true && source ./exportLocal.sh && ./initLocalTest.sh
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
"stable" has been added to your repositories
"bitnami" already exists with the same configuration, skipping
"prometheus-community" already exists with the same configuration, skipping
"grafana" already exists with the same configuration, skipping
"ingress-nginx" already exists with the same configuration, skipping
"jetstack" already exists with the same configuration, skipping
"galoy" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "galoy" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Removing charts/galoy/charts/common-0.10.0.tgz
Removing charts/galoy/charts/mongodb-10.15.2.tgz
Removing charts/galoy/charts/nginx-8.9.0.tgz
Removing charts/galoy/charts/redis-14.1.1.tgz
Removing charts/monitoring/charts/grafana-6.7.0.tgz
Removing charts/monitoring/charts/prometheus-13.6.0.tgz
Removing charts/monitoring/charts/prometheus-blackbox-exporter-4.10.2.tgz
Saving 5 charts
Downloading redis from repo https://charts.bitnami.com/bitnami
Downloading mongodb from repo https://charts.bitnami.com/bitnami
Downloading common from repo https://charts.bitnami.com/bitnami
Downloading nginx from repo https://charts.bitnami.com/bitnami
Already downloaded nginx from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
/Users/Emmett/dev/walsingh/galoy
Saving 3 charts
Downloading grafana from repo https://grafana.github.io/helm-charts
Downloading prometheus from repo https://prometheus-community.github.io/helm-charts
Downloading prometheus-blackbox-exporter from repo https://prometheus-community.github.io/helm-charts
Deleting outdated charts
/Users/Emmett/dev/walsingh/galoy
mkdir: tmp: File exists
Cloning into './tmp'...
remote: Repository not found.
fatal: repository 'https://github.com/galoymoney/configs/' not found
cp: ./tmp/*: No such file or directory


---
executing upgrade: helm upgrade -i -n=default bitcoind -f ./charts/configs/bitcoind/localdev.yaml -f ./charts/configs/bitcoind/regtest.yaml galoy/bitcoind --version=0.1.15
Release "bitcoind" has been upgraded. Happy Helming!
NAME: bitcoind
LAST DEPLOYED: Mon Jun 21 13:18:38 2021
NAMESPACE: default
STATUS: deployed
REVISION: 14
NOTES:
bitcoind RPC can be accessed via port  on the following DNS name from within your cluster:
bitcoind.default.svc.cluster.local

To connect to bitcoind RPC:

1. Forward the port for the node:

  $ kubectl port-forward --namespace default $(kubectl get pods --namespace default -l "app=bitcoind,release=bitcoind" -o jsonpath="{ .items[0].metadata.name }") 

2. Test connection with user and password provided in configuration file:

  $ curl --user rpcuser:rpcpassword -k http://127.0.0.1: --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;'
waiting for -n=default -l app.kubernetes.io/name=bitcoind
pod/bitcoind-0 condition met
waiting for pod deletion
timed out waiting for the condition on pods/lnd-0
timed out waiting for the condition on pods/lnd-outside-1-0
timed out waiting for the condition on pods/lnd-outside-2-0
error: the path "./charts/configs/lnd/templates" does not exist


---
executing upgrade: helm upgrade -i -n=default lnd --version=1.2.5 -f ./charts/configs/lnd/regtest.yaml -f ./charts/configs/lnd/localdev.yaml --set service.staticIP=192.168.49.2 galoy/lnd
Release "lnd" has been upgraded. Happy Helming!
NAME: lnd
LAST DEPLOYED: Mon Jun 21 13:35:29 2021
NAMESPACE: default
STATUS: deployed
REVISION: 11
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace default svc -w lnd'
  export SERVICE_IP=$(kubectl get svc --namespace default lnd --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:
2. To get the TLS, run:
export TLS=$(kubectl -n default exec lnd-0 -- base64 /data/.lnd/tls.cert | tr -d '\n\r')
3. To get the macaroon, run:
export MACAROON=$(kubectl exec -n default lnd-0 -- base64 /data/.lnd/data/chain/bitcoin/regtest/admin.macaroon | tr -d '\n\r')
4. To execute lncli against the pod, run the following commands:
kubectl -n default port-forward lnd-0 10009
lncli -n default help
5. To retrieve the seed for the lnd wallet, run:
kubectl -n default logs lnd-wallet-create
kubectl -n default delete pod lnd-wallet-create

Warning: Make sure you write/store the seed somewhere, because if lost you will not be able to retrieve it again, and you might end up losing all your funds.


---
executing upgrade: helm upgrade -i -n=default lnd-outside-1 --version=1.2.5 -f ./charts/configs/lnd/regtest.yaml -f ./charts/configs/lnd/localdev-outside.yaml --set service.staticIP=192.168.49.2 galoy/lnd
Release "lnd-outside-1" has been upgraded. Happy Helming!
NAME: lnd-outside-1
LAST DEPLOYED: Mon Jun 21 13:35:40 2021
NAMESPACE: default
STATUS: deployed
REVISION: 9
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace default svc -w lnd-outside-1'
  export SERVICE_IP=$(kubectl get svc --namespace default lnd-outside-1 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:
2. To get the TLS, run:
export TLS=$(kubectl -n default exec lnd-outside-1-0 -- base64 /data/.lnd/tls.cert | tr -d '\n\r')
3. To get the macaroon, run:
export MACAROON=$(kubectl exec -n default lnd-outside-1-0 -- base64 /data/.lnd/data/chain/bitcoin/regtest/admin.macaroon | tr -d '\n\r')
4. To execute lncli against the pod, run the following commands:
kubectl -n default port-forward lnd-outside-1-0 10009
lncli -n default help
5. To retrieve the seed for the lnd wallet, run:
kubectl -n default logs lnd-outside-1-wallet-create
kubectl -n default delete pod lnd-outside-1-wallet-create

Warning: Make sure you write/store the seed somewhere, because if lost you will not be able to retrieve it again, and you might end up losing all your funds.


---
executing upgrade: helm upgrade -i -n=default lnd-outside-2 --version=1.2.5 -f ./charts/configs/lnd/regtest.yaml -f ./charts/configs/lnd/localdev-outside.yaml --set service.staticIP=192.168.49.2 galoy/lnd
Release "lnd-outside-2" has been upgraded. Happy Helming!
NAME: lnd-outside-2
LAST DEPLOYED: Mon Jun 21 13:35:53 2021
NAMESPACE: default
STATUS: deployed
REVISION: 9
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace default svc -w lnd-outside-2'
  export SERVICE_IP=$(kubectl get svc --namespace default lnd-outside-2 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:
2. To get the TLS, run:
export TLS=$(kubectl -n default exec lnd-outside-2-0 -- base64 /data/.lnd/tls.cert | tr -d '\n\r')
3. To get the macaroon, run:
export MACAROON=$(kubectl exec -n default lnd-outside-2-0 -- base64 /data/.lnd/data/chain/bitcoin/regtest/admin.macaroon | tr -d '\n\r')
4. To execute lncli against the pod, run the following commands:
kubectl -n default port-forward lnd-outside-2-0 10009
lncli -n default help
5. To retrieve the seed for the lnd wallet, run:
kubectl -n default logs lnd-outside-2-wallet-create
kubectl -n default delete pod lnd-outside-2-wallet-create

Warning: Make sure you write/store the seed somewhere, because if lost you will not be able to retrieve it again, and you might end up losing all your funds.
waiting for -n=default -l app.kubernetes.io/name=lnd
pod/lnd-0 condition met
pod/lnd-outside-1-0 condition met
pod/lnd-outside-2-0 condition met


---
executing upgrade: helm upgrade -i -n=default galoy -f ./charts/galoy/regtest.yaml -f ./charts/galoy/localdev.yaml --set mongodb.auth.password=8XJkLaGsgk,mongodb.auth.rootPassword=zrRQsiHTNY,mongodb.auth.replicaSetKey=,image.tag= ./charts/galoy/
coalesce.go:200: warning: cannot overwrite table with non table for sysctls (map[])
coalesce.go:200: warning: cannot overwrite table with non table for sysctls (map[])
coalesce.go:200: warning: cannot overwrite table with non table for sysctls (map[])
coalesce.go:200: warning: cannot overwrite table with non table for sysctls (map[])
coalesce.go:200: warning: cannot overwrite table with non table for sysctls (map[])
coalesce.go:200: warning: cannot overwrite table with non table for sysctls (map[])
Release "galoy" has been upgraded. Happy Helming!
NAME: galoy
LAST DEPLOYED: Mon Jun 21 13:36:25 2021
NAMESPACE: default
STATUS: deployed
REVISION: 9
waiting for -n=default -l app.kubernetes.io/instance=galoy

````

**Comment by krtk6160** [comment] 2021-06-21 14:02
@walshe Did you check out the [caveats](https://github.com/GaloyMoney/galoy/blob/main/INSTALLATION.md#caveats) section?

**Comment by walshe** [comment] 2021-06-22 14:49
> @walshe Did you check out the [caveats](https://github.com/GaloyMoney/galoy/blob/main/INSTALLATION.md#caveats) section in INSTALLATION.md?

yes I added the other grep.. heres my latest run:

````
Emmett@MDs-MacBook-Pro galoy % node --version 
v14.0.0
Emmett@MDs-MacBook-Pro galoy % yarn add-charts
yarn run v1.22.10
$ export LOCAL=true && source ./exportLocal.sh && ./initLocalTest.sh
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
"stable" has been added to your repositories
"bitnami" already exists with the same configuration, skipping
"prometheus-community" already exists with the same configuration, skipping
"grafana" already exists with the same configuration, skipping
"ingress-nginx" already exists with the same configuration, skipping
"jetstack" already exists with the same configuration, skipping
"galoy" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "galoy" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Removing charts/galoy/charts/common-0.10.0.tgz
Removing charts/galoy/charts/mongodb-10.15.2.tgz
Removing charts/galoy/charts/nginx-8.9.0.tgz
Removing charts/galoy/charts/redis-14.1.1.tgz
Removing charts/monitoring/charts/grafana-6.7.0.tgz
Removing charts/monitoring/charts/prometheus-13.6.0.tgz
Removing charts/monitoring/charts/prometheus-blackbox-exporter-4.10.2.tgz
Saving 5 charts
Downloading redis from repo https://charts.bitnami.com/bitnami
Downloading mongodb from repo https://charts.bitnami.com/bitnami
Downloading common from repo https://charts.bitnami.com/bitnami
Downloading nginx from repo https://charts.bitnami.com/bitnami
Already downloaded nginx from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
/Users/Emmett/dev/walsingh/galoy
Saving 3 charts
Downloading grafana from repo https://grafana.github.io/helm-charts
Downloading prometheus from repo https://prometheus-community.github.io/helm-charts
Downloading prometheus-blackbox-exporter from repo https://prometheus-community.github.io/helm-charts
Deleting outdated charts
/Users/Emmett/dev/walsingh/galoy
error Command failed with exit code 89.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Emmett@MDs-MacBook-Pro galoy % 
````

**Comment by otech47** [comment] 2021-07-18 16:13
@walshe did you make sure your `minikube` instance was up and running?

https://minikube.sigs.k8s.io/docs/start/

The last command in Step 4 I run is `kubectl port-forward service/hello-minikube 7080:8080` and then in a new Terminal tab I try to run the `yarn add-charts` command

But then I see it seems to be getting stuck due to the https://github.com/galoymoney/configs/ repo being private.


![Screen Shot 2021-07-18 at 12 12 27 PM](https://user-images.githubusercontent.com/4914611/126074425-6c114806-410d-41db-9671-8816d978ac83.png)

I may try to replace the line in `exportLocal.sh` that exports `export CONFIG_REPO="https://github.com/GaloyMoney/configs"` to a new repo that I have access to or is public but not sure if there needs to be anything in there for this to work

**Comment by bodymindarts** [comment] 2021-07-18 18:35
What are you trying to achieve running galoy on Minikube? For local dev we have moved to a docker-composed based setup. See https://github.com/GaloyMoney/galoy/blob/main/DEV.md

**Comment by otech47** [comment] 2021-07-18 19:57
> What are you trying to achieve running galoy on Minikube? For local dev we have moved to a docker-composed based setup. See https://github.com/GaloyMoney/galoy/blob/main/DEV.md

I was just following this installation guide: https://github.com/GaloyMoney/galoy/blob/main/INSTALLATION.md

**Comment by bodymindarts** [comment] 2021-07-18 20:10
If your goal is to achieve a local dev-loop that is no longer the recommended way to achieve it.

**Comment by nicolasburtey** [comment] 2021-11-04 18:25
our build / dev system has been completely revamp since this issue has been created. closing it now, but in case the issue is still present feel free to reopen @walshe @otech47

**Closed by nicolasburtey** 2021-11-04 18:25 UTC

**Comment by walshe** [comment] 2021-11-04 18:29
thanks @nicolasburtey , I must get back to it. Have got sidetracked with a bunch of other side projects the last few months :(
